### ISSUE TITLE
Support for V3S145

### ISSUE THREAD

**Issue by QAU3** [SICKAG/sick_visionary_samples#11]
Hi,
I was wondering if there is/ there will be any support for the V3S145 cameras. 

I have two cameras, this specific model and B-Two.  For the second one the python/c++ support is ok.  But for the first one, not even interpreters or scheme to make useful the mv3 files it produces. 

Maybe I am missing something, it would be great if you can point me to the right documentation.

**Comment by xfealal** [comment]
Hello @QAU3, 
The C++/Python samples in this repository are only compatible with **Visionary-T Mini CX (V3S105-1AAAAAA)** which uses the underlying CoLa communication interface. Your camera is the Visionary-T Mini AP (V3S145-1AAAAAA) which doesn't support the CoLa communication interface.  
Support for GigE communication including a similar set of programming samples for the Visionary-T Mini AP is expected in the near future.  
Best regards.
