### ISSUE TITLE
multiple definition with BlobServerConfig when compiling static lib

### ISSUE THREAD

**Issue by arrfou99** [SICKAG/sick_visionary_samples#2]
When compiling this package as a static lib, I get multiple definition error of methods that are inside /shared/BlobServerConfig.h

I propose to add keyword inline to all methods or to have a cpp file of BlobServerConfig.h 

I am compiling this package as static lib since it has more functionalities that I can use compared with the base package. 

thank you

**Comment by xfealal** [comment]
Dear @arrfou99,

Thank you for your suggestion. We understand the issue you’re facing when compiling the package as a static library. Your proposal is appreciated. We’ll review this and make the necessary changes.

**Comment by xfealal** [comment]
Dear @arrfou99,
We want to inform you that we have incorporated your suggestions into the current release (1.1.0). The shared/cpp folder is now compiled into a static library called shared_cpp_utils. We hope this resolves the issues you encountered. Your feedback is appreciated.

**Comment by arrfou99** [comment]
Great, thank you. we can close the issue.
