### ISSUE TITLE
Missing head file in C++'s sample code

### ISSUE THREAD

**Issue by jethro-huang-hub** [SICKAG/sick_visionary_samples#3]
Missing head file in C++'s sample code, which could be found in ROS's tank called "sick_visionary-cpp_shared".
![微信图片_20240717111744](https://github.com/user-attachments/assets/d9d21f0a-2fc5-495e-9c87-82ddbb1e3e14)

**Comment by zimmefaSICKAG** [comment]
Please note that the ROS driver for Visionary-T Mini CX and Visionary-S CX that can be found [here](https://github.com/SICKAG/sick_visionary_ros), still requires [sick_visionary_cpp_shared](https://github.com/SICKAG/sick_visionary_cpp_shared). It won't work with the samples and specifically the _base_ interfaces referred to in this repository.

Does this answer your question?

**Comment by peichtoSICKAG** [comment]
Please note for the new sick_visionary_samples the sick_visionary_cpp_shared library was refactored to sick_visionary_cpp_base changing some interfaces to be more verbose, which is reference as submodule and needs initialization by either using ```git clone --recursive``` or after a regular clone ```git submodule update --init --recursive```.

Unfortunately during the update repetitive sample code was collected in a local shared folder. This was originially intended only for reuse between the samples but has now been refactored to a standalone library as requested.
