### ISSUE TITLE
Inquiry About 3D Data Access and Obstacle Detection with Sick Visionary T-mini AP

### ISSUE THREAD

**Issue by oliveyoung123** [SICKAG/sick_visionary_samples#5]
Hello,

I am currently evaluating the Sick Visionary T-mini AP for obstacle detection in a factory logistics robot in South Korea. (Product Information: https://cdn.sick.com/media/docs/5/15/615/quickstart_visionary_t_mini_ap_ko_im0102615.pdf)

My main objectives are as follows:

- Obstacle Detection: Detecting objects and floor openings (holes) that may appear during the robot's movement.
3D Data Access for Algorithm Development: I need to access the 3D data of detected objects to develop a detection algorithm, and if the data received does not meet our needs, I plan to integrate LiDAR data.
Despite multiple attempts to access the data, I have been unsuccessful. I reached out to the technical sales team at the South Korean branch and received the following responses:

- 3D Data Access: They informed me that it is not possible to receive 3D data directly from the AP model. They stated that the system only provides information on whether an obstacle is present within a defined area. For example, if equipment appears within the defined area, it is recognized as an obstacle, even if it should be excluded. There is no function to exclude specific objects.
Detection of Openings (Holes): They also mentioned that the system cannot detect openings other than the floor and lacks this functionality.

Given that I can only receive information about the presence of obstacles, and not the 3D data related to them, I find it difficult to understand the limitations. Is it true that the T-mini AP model does not allow for 3D data access or utilization? If that is the case, could you recommend the most suitable sensor for my current needs?

Your assistance would be greatly appreciated.

**Comment by xfealal** [comment]
Hello @oliveyoung123,

Thank you for your inquiry. This repository specifically handles requests related to the Sick Visionary samples (Visionary-T Mini **CX** and Visionary-S **CX**).

For further assistance with your Visionary-T Mini **AP** and to explore alternative solutions that might better meet your needs, I recommend reaching out to the support team through the SICK support portal: [https://support.sick.com/](https://support.sick.com/). They will be able to provide you with more detailed information and guidance.

I hope this helps, and I wish you the best of luck with your project!

Best regards.
