### ISSUE TITLE
Snapshot mode: it gives us the error messages we see when acquiring the first frame.

### ISSUE THREAD

**Issue by arrfou99** [SICKAG/sick_visionary_samples#7]
when using the Visionary T mini camera in snapshot mode, the following code is responsible for setting up the transport protocol and the TCP port for blob data transmission using the following two CoLa commands:

(https://github.com/SICKAG/sick_visionary_samples/blob/71f25dab3411d8151874eb1ed687ecf1264ce2f0/image_streaming_and_storing/cpp/snapshots.cpp#L82-L83)

it gives us the error messages we see when acquiring the first frame.

```cmd
Failure writing BlobTransportProtocolAPI: 10
Failure writing BlobTcpPortAPI: 10
```

As I understand it, these errors print messages occur because the driver uses the first frame to verify that a blob (encoded data) is being received.

I propose to have a mechanism that distinguishes whether the first frame has been processed, avoiding these errors prints.

**Comment by xfealal** [comment]
Hello @arrfou99,

Lines 82 and 83 are sending two CoLa commands to the device before any streaming is active.

The “10” you’re seeing refers to the following error code:

```
/// It is not allowed to write values to this variable. Probably the variable is defined as read-only
VARIABLE_WRITE_ACCESS_DENIED = 10,
```

I am not sure when exactly this error message gets printed. Is it after you’ve already received a frame? Could you provide us with the full console output?

**Comment by arrfou99** [comment]
OK, I will reproduce the error and paste it here. It happens only once before receiving any frame.   
thanks.

**Comment by arrfou99** [comment]
here is the output using the snapshot mode $./snapshots 

`

Failure writing BlobTransportProtocolAPI: 10
Failure writing BlobTcpPortAPI: 10
Frame received in snapshot mode, frame #81474
Writing frame to 81474-pointcloud.ply
Finished writing frame to 81474-pointcloud.ply
Frame received in snapshot mode, frame #81478
Writing frame to 81478-pointcloud.ply
Finished writing frame to 81478-pointcloud.ply
Frame received in snapshot mode, frame #81490
Writing frame to 81490-pointcloud.ply
Finished writing frame to 81490-pointcloud.ply
Frame received in snapshot mode, frame #81503
Writing frame to 81503-pointcloud.ply
Finished writing frame to 81503-pointcloud.ply
Frame received in snapshot mode, frame #81516
Writing frame to 81516-pointcloud.ply
Finished writing frame to 81516-pointcloud.ply
Failure writing BlobTcpPortAPI: 10
exit code 0`

**Comment by arrfou99** [comment]
Ok It could be because of the password, I will test it and update here

**Comment by arrfou99** [comment]
The issue was from using another password, I can confirm that changing PW to default one or using minimum required user level solve the issue. 

We can close this issue.

Thank very much.
